### ISSUE TITLE
Kanban Set-up

### ISSUE THREAD

**Issue by Lizdev-05** [Lizdev-05/Recipe-app#11]
There are 2 members in our team. @hammaazarok has been assigned to Team Member 1 task, and @Lizdev-05 to Team Member 2. Here is the [link](https://github.com/Lizdev-05/Recipe-app/projects/1) to the project

**Comment by rloterh** [comment]
## Status: Approved :heavy_check_mark:

Hi Hamma & Elizabeth,  

Your project is complete! 🍾🍾 Congratulations!  🎉💯🌟 

## Highlights 👍
- Fair distribution of tasks
- Cards corresponds with project requirements
- Good descriptive board title and description of tasks

Keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
